#!/usr/bin/env bash

[ -n "$CI" ] && exit 0

echo "Formatting Staged Files ..."

diff=$(git diff --name-only --cached)

[[ -z "$var" ]] && exit 0

java -jar tools/google-java-format/google-java-format.jar --replace "$diff"
git add "$diff"

echo "Linting ..."
./gradlew lint -q
